module.exports = {
  "msUPN": "Microsoft User Principal Name",
  "msSmartcardLogin": "Microsoft Smartcard Login",
  "ITU-T": "itu-t",
  "ISO": "iso",
  "JOINT-ISO-ITU-T": "joint-iso-itu-t",
  "member-body": "ISO Member Body",
  "identified-organization": "identified-organization",
  "GMAC": "gmac",
  "HMAC-MD5": "hmac-md5",
  "HMAC-SHA1": "hmac-sha1",
  "x509ExtAdmission": "Professional Information or basis for Admission",
  "certicom-arc": "certicom-arc",
  "ieee": "ieee",
  "ieee-siswg": "IEEE Security in Storage Working Group",
  "international-organizations": "International Organizations",
  "wap": "wap",
  "wap-wsg": "wap-wsg",
  "selected-attribute-types": "Selected Attribute Types",
  "clearance": "clearance",
  "ISO-US": "ISO US Member Body",
  "X9-57": "X9.57",
  "X9cm": "X9.57 CM ?",
  "ISO-CN": "ISO CN Member Body",
  "oscca": "oscca",
  "sm-scheme": "sm-scheme",
  "DSA": "dsaEncryption",
  "DSA-SHA1": "dsaWithSHA1",
  "ansi-X9-62": "ANSI X9.62",
  "prime-field": "prime-field",
  "characteristic-two-field": "characteristic-two-field",
  "id-characteristic-two-basis": "id-characteristic-two-basis",
  "onBasis": "onBasis",
  "tpBasis": "tpBasis",
  "ppBasis": "ppBasis",
  "id-ecPublicKey": "id-ecPublicKey",
  "c2pnb163v1": "c2pnb163v1",
  "c2pnb163v2": "c2pnb163v2",
  "c2pnb163v3": "c2pnb163v3",
  "c2pnb176v1": "c2pnb176v1",
  "c2tnb191v1": "c2tnb191v1",
  "c2tnb191v2": "c2tnb191v2",
  "c2tnb191v3": "c2tnb191v3",
  "c2onb191v4": "c2onb191v4",
  "c2onb191v5": "c2onb191v5",
  "c2pnb208w1": "c2pnb208w1",
  "c2tnb239v1": "c2tnb239v1",
  "c2tnb239v2": "c2tnb239v2",
  "c2tnb239v3": "c2tnb239v3",
  "c2onb239v4": "c2onb239v4",
  "c2onb239v5": "c2onb239v5",
  "c2pnb272w1": "c2pnb272w1",
  "c2pnb304w1": "c2pnb304w1",
  "c2tnb359v1": "c2tnb359v1",
  "c2pnb368w1": "c2pnb368w1",
  "c2tnb431r1": "c2tnb431r1",
  "prime192v1": "prime192v1",
  "prime192v2": "prime192v2",
  "prime192v3": "prime192v3",
  "prime239v1": "prime239v1",
  "prime239v2": "prime239v2",
  "prime239v3": "prime239v3",
  "prime256v1": "prime256v1",
  "ecdsa-with-SHA1": "ecdsa-with-SHA1",
  "ecdsa-with-Recommended": "ecdsa-with-Recommended",
  "ecdsa-with-Specified": "ecdsa-with-Specified",
  "ecdsa-with-SHA224": "ecdsa-with-SHA224",
  "ecdsa-with-SHA256": "ecdsa-with-SHA256",
  "ecdsa-with-SHA384": "ecdsa-with-SHA384",
  "ecdsa-with-SHA512": "ecdsa-with-SHA512",
  "secp112r1": "secp112r1",
  "secp112r2": "secp112r2",
  "secp128r1": "secp128r1",
  "secp128r2": "secp128r2",
  "secp160k1": "secp160k1",
  "secp160r1": "secp160r1",
  "secp160r2": "secp160r2",
  "secp192k1": "secp192k1",
  "secp224k1": "secp224k1",
  "secp224r1": "secp224r1",
  "secp256k1": "secp256k1",
  "secp384r1": "secp384r1",
  "secp521r1": "secp521r1",
  "sect113r1": "sect113r1",
  "sect113r2": "sect113r2",
  "sect131r1": "sect131r1",
  "sect131r2": "sect131r2",
  "sect163k1": "sect163k1",
  "sect163r1": "sect163r1",
  "sect163r2": "sect163r2",
  "sect193r1": "sect193r1",
  "sect193r2": "sect193r2",
  "sect233k1": "sect233k1",
  "sect233r1": "sect233r1",
  "sect239k1": "sect239k1",
  "sect283k1": "sect283k1",
  "sect283r1": "sect283r1",
  "sect409k1": "sect409k1",
  "sect409r1": "sect409r1",
  "sect571k1": "sect571k1",
  "sect571r1": "sect571r1",
  "wap-wsg-idm-ecid-wtls1": "wap-wsg-idm-ecid-wtls1",
  "wap-wsg-idm-ecid-wtls3": "wap-wsg-idm-ecid-wtls3",
  "wap-wsg-idm-ecid-wtls4": "wap-wsg-idm-ecid-wtls4",
  "wap-wsg-idm-ecid-wtls5": "wap-wsg-idm-ecid-wtls5",
  "wap-wsg-idm-ecid-wtls6": "wap-wsg-idm-ecid-wtls6",
  "wap-wsg-idm-ecid-wtls7": "wap-wsg-idm-ecid-wtls7",
  "wap-wsg-idm-ecid-wtls8": "wap-wsg-idm-ecid-wtls8",
  "wap-wsg-idm-ecid-wtls9": "wap-wsg-idm-ecid-wtls9",
  "wap-wsg-idm-ecid-wtls10": "wap-wsg-idm-ecid-wtls10",
  "wap-wsg-idm-ecid-wtls11": "wap-wsg-idm-ecid-wtls11",
  "wap-wsg-idm-ecid-wtls12": "wap-wsg-idm-ecid-wtls12",
  "CAST5-CBC": "cast5-cbc",
  "CAST5-ECB": "cast5-ecb",
  "CAST5-CFB": "cast5-cfb",
  "CAST5-OFB": "cast5-ofb",
  "id-PasswordBasedMAC": "password based MAC",
  "id-DHBasedMac": "Diffie-Hellman based MAC",
  "rsadsi": "RSA Data Security, Inc.",
  "pkcs": "RSA Data Security, Inc. PKCS",
  "pkcs1": "pkcs1",
  "RSA-MD2": "md2WithRSAEncryption",
  "RSA-MD4": "md4WithRSAEncryption",
  "RSA-MD5": "md5WithRSAEncryption",
  "RSA-SHA1": "sha1WithRSAEncryption",
  "RSAES-OAEP": "rsaesOaep",
  "MGF1": "mgf1",
  "PSPECIFIED": "pSpecified",
  "RSASSA-PSS": "rsassaPss",
  "RSA-SHA256": "sha256WithRSAEncryption",
  "RSA-SHA384": "sha384WithRSAEncryption",
  "RSA-SHA512": "sha512WithRSAEncryption",
  "RSA-SHA224": "sha224WithRSAEncryption",
  "RSA-SHA512/224": "sha512-224WithRSAEncryption",
  "RSA-SHA512/256": "sha512-256WithRSAEncryption",
  "pkcs3": "pkcs3",
  "pkcs5": "pkcs5",
  "PBE-MD2-DES": "pbeWithMD2AndDES-CBC",
  "PBE-MD5-DES": "pbeWithMD5AndDES-CBC",
  "PBE-MD2-RC2-64": "pbeWithMD2AndRC2-CBC",
  "PBE-MD5-RC2-64": "pbeWithMD5AndRC2-CBC",
  "PBE-SHA1-DES": "pbeWithSHA1AndDES-CBC",
  "PBE-SHA1-RC2-64": "pbeWithSHA1AndRC2-CBC",
  "pkcs7": "pkcs7",
  "pkcs9": "pkcs9",
  "extReq": "Extension Request",
  "SMIME-CAPS": "S/MIME Capabilities",
  "SMIME": "S/MIME",
  "id-smime-mod": "id-smime-mod",
  "id-smime-ct": "id-smime-ct",
  "id-smime-aa": "id-smime-aa",
  "id-smime-alg": "id-smime-alg",
  "id-smime-cd": "id-smime-cd",
  "id-smime-spq": "id-smime-spq",
  "id-smime-cti": "id-smime-cti",
  "id-smime-mod-cms": "id-smime-mod-cms",
  "id-smime-mod-ess": "id-smime-mod-ess",
  "id-smime-mod-oid": "id-smime-mod-oid",
  "id-smime-mod-msg-v3": "id-smime-mod-msg-v3",
  "id-smime-mod-ets-eSignature-88": "id-smime-mod-ets-eSignature-88",
  "id-smime-mod-ets-eSignature-97": "id-smime-mod-ets-eSignature-97",
  "id-smime-mod-ets-eSigPolicy-88": "id-smime-mod-ets-eSigPolicy-88",
  "id-smime-mod-ets-eSigPolicy-97": "id-smime-mod-ets-eSigPolicy-97",
  "id-smime-ct-receipt": "id-smime-ct-receipt",
  "id-smime-ct-authData": "id-smime-ct-authData",
  "id-smime-ct-publishCert": "id-smime-ct-publishCert",
  "id-smime-ct-TSTInfo": "id-smime-ct-TSTInfo",
  "id-smime-ct-TDTInfo": "id-smime-ct-TDTInfo",
  "id-smime-ct-contentInfo": "id-smime-ct-contentInfo",
  "id-smime-ct-DVCSRequestData": "id-smime-ct-DVCSRequestData",
  "id-smime-ct-DVCSResponseData": "id-smime-ct-DVCSResponseData",
  "id-smime-ct-compressedData": "id-smime-ct-compressedData",
  "id-smime-ct-contentCollection": "id-smime-ct-contentCollection",
  "id-smime-ct-authEnvelopedData": "id-smime-ct-authEnvelopedData",
  "id-ct-routeOriginAuthz": "id-ct-routeOriginAuthz",
  "id-ct-rpkiManifest": "id-ct-rpkiManifest",
  "id-ct-asciiTextWithCRLF": "id-ct-asciiTextWithCRLF",
  "id-ct-xml": "id-ct-xml",
  "id-ct-rpkiGhostbusters": "id-ct-rpkiGhostbusters",
  "id-ct-resourceTaggedAttest": "id-ct-resourceTaggedAttest",
  "id-ct-geofeedCSVwithCRLF": "id-ct-geofeedCSVwithCRLF",
  "id-ct-signedChecklist": "id-ct-signedChecklist",
  "id-ct-ASPA": "id-ct-ASPA",
  "id-ct-signedTAL": "id-ct-signedTAL",
  "id-ct-rpkiSignedPrefixList": "id-ct-rpkiSignedPrefixList",
  "id-smime-aa-receiptRequest": "id-smime-aa-receiptRequest",
  "id-smime-aa-securityLabel": "id-smime-aa-securityLabel",
  "id-smime-aa-mlExpandHistory": "id-smime-aa-mlExpandHistory",
  "id-smime-aa-contentHint": "id-smime-aa-contentHint",
  "id-smime-aa-msgSigDigest": "id-smime-aa-msgSigDigest",
  "id-smime-aa-encapContentType": "id-smime-aa-encapContentType",
  "id-smime-aa-contentIdentifier": "id-smime-aa-contentIdentifier",
  "id-smime-aa-macValue": "id-smime-aa-macValue",
  "id-smime-aa-equivalentLabels": "id-smime-aa-equivalentLabels",
  "id-smime-aa-contentReference": "id-smime-aa-contentReference",
  "id-smime-aa-encrypKeyPref": "id-smime-aa-encrypKeyPref",
  "id-smime-aa-signingCertificate": "id-smime-aa-signingCertificate",
  "id-smime-aa-smimeEncryptCerts": "id-smime-aa-smimeEncryptCerts",
  "id-smime-aa-timeStampToken": "id-smime-aa-timeStampToken",
  "id-smime-aa-ets-sigPolicyId": "id-smime-aa-ets-sigPolicyId",
  "id-smime-aa-ets-commitmentType": "id-smime-aa-ets-commitmentType",
  "id-smime-aa-ets-signerLocation": "id-smime-aa-ets-signerLocation",
  "id-smime-aa-ets-signerAttr": "id-smime-aa-ets-signerAttr",
  "id-smime-aa-ets-otherSigCert": "id-smime-aa-ets-otherSigCert",
  "id-smime-aa-ets-contentTimestamp": "id-smime-aa-ets-contentTimestamp",
  "id-smime-aa-ets-CertificateRefs": "id-smime-aa-ets-CertificateRefs",
  "id-smime-aa-ets-RevocationRefs": "id-smime-aa-ets-RevocationRefs",
  "id-smime-aa-ets-certValues": "id-smime-aa-ets-certValues",
  "id-smime-aa-ets-revocationValues": "id-smime-aa-ets-revocationValues",
  "id-smime-aa-ets-escTimeStamp": "id-smime-aa-ets-escTimeStamp",
  "id-smime-aa-ets-certCRLTimestamp": "id-smime-aa-ets-certCRLTimestamp",
  "id-smime-aa-ets-archiveTimeStamp": "id-smime-aa-ets-archiveTimeStamp",
  "id-smime-aa-signatureType": "id-smime-aa-signatureType",
  "id-smime-aa-dvcs-dvc": "id-smime-aa-dvcs-dvc",
  "id-aa-ets-attrCertificateRefs": "id-aa-ets-attrCertificateRefs",
  "id-aa-ets-attrRevocationRefs": "id-aa-ets-attrRevocationRefs",
  "id-smime-aa-signingCertificateV2": "id-smime-aa-signingCertificateV2",
  "id-aa-ets-archiveTimestampV2": "id-aa-ets-archiveTimestampV2",
  "id-smime-alg-ESDHwith3DES": "id-smime-alg-ESDHwith3DES",
  "id-smime-alg-ESDHwithRC2": "id-smime-alg-ESDHwithRC2",
  "id-smime-alg-3DESwrap": "id-smime-alg-3DESwrap",
  "id-smime-alg-RC2wrap": "id-smime-alg-RC2wrap",
  "id-smime-alg-ESDH": "id-smime-alg-ESDH",
  "id-smime-alg-CMS3DESwrap": "id-smime-alg-CMS3DESwrap",
  "id-smime-alg-CMSRC2wrap": "id-smime-alg-CMSRC2wrap",
  "id-alg-PWRI-KEK": "id-alg-PWRI-KEK",
  "id-smime-cd-ldap": "id-smime-cd-ldap",
  "id-smime-spq-ets-sqt-uri": "id-smime-spq-ets-sqt-uri",
  "id-smime-spq-ets-sqt-unotice": "id-smime-spq-ets-sqt-unotice",
  "id-smime-cti-ets-proofOfOrigin": "id-smime-cti-ets-proofOfOrigin",
  "id-smime-cti-ets-proofOfReceipt": "id-smime-cti-ets-proofOfReceipt",
  "id-smime-cti-ets-proofOfDelivery": "id-smime-cti-ets-proofOfDelivery",
  "id-smime-cti-ets-proofOfSender": "id-smime-cti-ets-proofOfSender",
  "id-smime-cti-ets-proofOfApproval": "id-smime-cti-ets-proofOfApproval",
  "id-smime-cti-ets-proofOfCreation": "id-smime-cti-ets-proofOfCreation",
  "CSPName": "Microsoft CSP Name",
  "LocalKeySet": "Microsoft Local Key set",
  "id-aa-CMSAlgorithmProtection": "id-aa-CMSAlgorithmProtection",
  "PBE-SHA1-RC4-128": "pbeWithSHA1And128BitRC4",
  "PBE-SHA1-RC4-40": "pbeWithSHA1And40BitRC4",
  "PBE-SHA1-3DES": "pbeWithSHA1And3-KeyTripleDES-CBC",
  "PBE-SHA1-2DES": "pbeWithSHA1And2-KeyTripleDES-CBC",
  "PBE-SHA1-RC2-128": "pbeWithSHA1And128BitRC2-CBC",
  "PBE-SHA1-RC2-40": "pbeWithSHA1And40BitRC2-CBC",
  "MD2": "md2",
  "MD4": "md4",
  "MD5": "md5",
  "MD5-SHA1": "md5-sha1",
  "SM2": "sm2",
  "SM3": "sm3",
  "RSA-SM3": "sm3WithRSAEncryption",
  "SM2-SM3": "SM2-with-SM3",
  "RC2-CBC": "rc2-cbc",
  "RC2-ECB": "rc2-ecb",
  "RC2-CFB": "rc2-cfb",
  "RC2-OFB": "rc2-ofb",
  "RC2-40-CBC": "rc2-40-cbc",
  "RC2-64-CBC": "rc2-64-cbc",
  "RC4": "rc4",
  "RC4-40": "rc4-40",
  "DES-EDE3-CBC": "des-ede3-cbc",
  "RC5-CBC": "rc5-cbc",
  "RC5-ECB": "rc5-ecb",
  "RC5-CFB": "rc5-cfb",
  "RC5-OFB": "rc5-ofb",
  "msExtReq": "Microsoft Extension Request",
  "msCodeInd": "Microsoft Individual Code Signing",
  "msCodeCom": "Microsoft Commercial Code Signing",
  "msCTLSign": "Microsoft Trust List Signing",
  "msSGC": "Microsoft Server Gated Crypto",
  "msEFS": "Microsoft Encrypted File System",
  "ms-ntds-sec-ext": "Microsoft NTDS CA Extension",
  "ms-ntds-obj-sid": "Microsoft NTDS AD objectSid",
  "ms-cert-templ": "Microsoft certificate template",
  "ms-app-policies": "Microsoft Application Policies Extension",
  "IDEA-CBC": "idea-cbc",
  "IDEA-ECB": "idea-ecb",
  "IDEA-CFB": "idea-cfb",
  "IDEA-OFB": "idea-ofb",
  "BF-CBC": "bf-cbc",
  "BF-ECB": "bf-ecb",
  "BF-CFB": "bf-cfb",
  "BF-OFB": "bf-ofb",
  "PKIX": "PKIX",
  "id-pkix-mod": "id-pkix-mod",
  "id-pe": "id-pe",
  "id-qt": "id-qt",
  "id-kp": "id-kp",
  "id-it": "id-it",
  "id-pkip": "id-pkip",
  "id-alg": "id-alg",
  "id-cmc": "id-cmc",
  "id-on": "id-on",
  "id-pda": "id-pda",
  "id-aca": "id-aca",
  "id-qcs": "id-qcs",
  "id-cp": "id-cp",
  "id-cct": "id-cct",
  "id-ppl": "id-ppl",
  "id-ad": "id-ad",
  "id-pkix1-explicit-88": "id-pkix1-explicit-88",
  "id-pkix1-implicit-88": "id-pkix1-implicit-88",
  "id-pkix1-explicit-93": "id-pkix1-explicit-93",
  "id-pkix1-implicit-93": "id-pkix1-implicit-93",
  "id-mod-crmf": "id-mod-crmf",
  "id-mod-cmc": "id-mod-cmc",
  "id-mod-kea-profile-88": "id-mod-kea-profile-88",
  "id-mod-kea-profile-93": "id-mod-kea-profile-93",
  "id-mod-cmp": "id-mod-cmp",
  "id-mod-qualified-cert-88": "id-mod-qualified-cert-88",
  "id-mod-qualified-cert-93": "id-mod-qualified-cert-93",
  "id-mod-attribute-cert": "id-mod-attribute-cert",
  "id-mod-timestamp-protocol": "id-mod-timestamp-protocol",
  "id-mod-ocsp": "id-mod-ocsp",
  "id-mod-dvcs": "id-mod-dvcs",
  "id-mod-cmp2000": "id-mod-cmp2000",
  "id-mod-cmp2000-02": "id-mod-cmp2000-02",
  "id-mod-cmp2021-88": "id-mod-cmp2021-88",
  "id-mod-cmp2021-02": "id-mod-cmp2021-02",
  "authorityInfoAccess": "Authority Information Access",
  "biometricInfo": "Biometric Info",
  "qcStatements": "qcStatements",
  "ac-auditEntity": "ac-auditEntity",
  "ac-targeting": "ac-targeting",
  "aaControls": "aaControls",
  "sbgp-ipAddrBlock": "sbgp-ipAddrBlock",
  "sbgp-autonomousSysNum": "sbgp-autonomousSysNum",
  "sbgp-routerIdentifier": "sbgp-routerIdentifier",
  "ac-proxying": "ac-proxying",
  "subjectInfoAccess": "Subject Information Access",
  "proxyCertInfo": "Proxy Certificate Information",
  "tlsfeature": "TLS Feature",
  "sbgp-ipAddrBlockv2": "sbgp-ipAddrBlockv2",
  "sbgp-autonomousSysNumv2": "sbgp-autonomousSysNumv2",
  "id-qt-cps": "Policy Qualifier CPS",
  "id-qt-unotice": "Policy Qualifier User Notice",
  "textNotice": "textNotice",
  "serverAuth": "TLS Web Server Authentication",
  "clientAuth": "TLS Web Client Authentication",
  "codeSigning": "Code Signing",
  "emailProtection": "E-mail Protection",
  "ipsecEndSystem": "IPSec End System",
  "ipsecTunnel": "IPSec Tunnel",
  "ipsecUser": "IPSec User",
  "timeStamping": "Time Stamping",
  "OCSPSigning": "OCSP Signing",
  "DVCS": "dvcs",
  "ipsecIKE": "ipsec Internet Key Exchange",
  "capwapAC": "Ctrl/provision WAP Access",
  "capwapWTP": "Ctrl/Provision WAP Termination",
  "secureShellClient": "SSH Client",
  "secureShellServer": "SSH Server",
  "sendRouter": "Send Router",
  "sendProxiedRouter": "Send Proxied Router",
  "sendOwner": "Send Owner",
  "sendProxiedOwner": "Send Proxied Owner",
  "cmcCA": "CMC Certificate Authority",
  "cmcRA": "CMC Registration Authority",
  "cmcArchive": "CMC Archive Server",
  "id-kp-bgpsec-router": "BGPsec Router",
  "id-kp-BrandIndicatorforMessageIdentification": "Brand Indicator for Message Identification",
  "cmKGA": "Certificate Management Key Generation Authority",
  "id-it-caProtEncCert": "id-it-caProtEncCert",
  "id-it-signKeyPairTypes": "id-it-signKeyPairTypes",
  "id-it-encKeyPairTypes": "id-it-encKeyPairTypes",
  "id-it-preferredSymmAlg": "id-it-preferredSymmAlg",
  "id-it-caKeyUpdateInfo": "id-it-caKeyUpdateInfo",
  "id-it-currentCRL": "id-it-currentCRL",
  "id-it-unsupportedOIDs": "id-it-unsupportedOIDs",
  "id-it-subscriptionRequest": "id-it-subscriptionRequest",
  "id-it-subscriptionResponse": "id-it-subscriptionResponse",
  "id-it-keyPairParamReq": "id-it-keyPairParamReq",
  "id-it-keyPairParamRep": "id-it-keyPairParamRep",
  "id-it-revPassphrase": "id-it-revPassphrase",
  "id-it-implicitConfirm": "id-it-implicitConfirm",
  "id-it-confirmWaitTime": "id-it-confirmWaitTime",
  "id-it-origPKIMessage": "id-it-origPKIMessage",
  "id-it-suppLangTags": "id-it-suppLangTags",
  "id-it-caCerts": "id-it-caCerts",
  "id-it-rootCaKeyUpdate": "id-it-rootCaKeyUpdate",
  "id-it-certReqTemplate": "id-it-certReqTemplate",
  "id-it-rootCaCert": "id-it-rootCaCert",
  "id-it-certProfile": "id-it-certProfile",
  "id-it-crlStatusList": "id-it-crlStatusList",
  "id-it-crls": "id-it-crls",
  "id-regCtrl": "id-regCtrl",
  "id-regInfo": "id-regInfo",
  "id-regCtrl-regToken": "id-regCtrl-regToken",
  "id-regCtrl-authenticator": "id-regCtrl-authenticator",
  "id-regCtrl-pkiPublicationInfo": "id-regCtrl-pkiPublicationInfo",
  "id-regCtrl-pkiArchiveOptions": "id-regCtrl-pkiArchiveOptions",
  "id-regCtrl-oldCertID": "id-regCtrl-oldCertID",
  "id-regCtrl-protocolEncrKey": "id-regCtrl-protocolEncrKey",
  "id-regCtrl-altCertTemplate": "id-regCtrl-altCertTemplate",
  "id-regCtrl-algId": "id-regCtrl-algId",
  "id-regCtrl-rsaKeyLen": "id-regCtrl-rsaKeyLen",
  "id-regInfo-utf8Pairs": "id-regInfo-utf8Pairs",
  "id-regInfo-certReq": "id-regInfo-certReq",
  "id-alg-des40": "id-alg-des40",
  "id-alg-noSignature": "id-alg-noSignature",
  "id-alg-dh-sig-hmac-sha1": "id-alg-dh-sig-hmac-sha1",
  "id-alg-dh-pop": "id-alg-dh-pop",
  "id-cmc-statusInfo": "id-cmc-statusInfo",
  "id-cmc-identification": "id-cmc-identification",
  "id-cmc-identityProof": "id-cmc-identityProof",
  "id-cmc-dataReturn": "id-cmc-dataReturn",
  "id-cmc-transactionId": "id-cmc-transactionId",
  "id-cmc-senderNonce": "id-cmc-senderNonce",
  "id-cmc-recipientNonce": "id-cmc-recipientNonce",
  "id-cmc-addExtensions": "id-cmc-addExtensions",
  "id-cmc-encryptedPOP": "id-cmc-encryptedPOP",
  "id-cmc-decryptedPOP": "id-cmc-decryptedPOP",
  "id-cmc-lraPOPWitness": "id-cmc-lraPOPWitness",
  "id-cmc-getCert": "id-cmc-getCert",
  "id-cmc-getCRL": "id-cmc-getCRL",
  "id-cmc-revokeRequest": "id-cmc-revokeRequest",
  "id-cmc-regInfo": "id-cmc-regInfo",
  "id-cmc-responseInfo": "id-cmc-responseInfo",
  "id-cmc-queryPending": "id-cmc-queryPending",
  "id-cmc-popLinkRandom": "id-cmc-popLinkRandom",
  "id-cmc-popLinkWitness": "id-cmc-popLinkWitness",
  "id-cmc-confirmCertAcceptance": "id-cmc-confirmCertAcceptance",
  "id-on-personalData": "id-on-personalData",
  "id-on-permanentIdentifier": "Permanent Identifier",
  "id-on-xmppAddr": "XmppAddr",
  "id-on-dnsSRV": "SRVName",
  "id-on-NAIRealm": "NAIRealm",
  "id-on-SmtpUTF8Mailbox": "Smtp UTF8 Mailbox",
  "id-pda-dateOfBirth": "id-pda-dateOfBirth",
  "id-pda-placeOfBirth": "id-pda-placeOfBirth",
  "id-pda-gender": "id-pda-gender",
  "id-pda-countryOfCitizenship": "id-pda-countryOfCitizenship",
  "id-pda-countryOfResidence": "id-pda-countryOfResidence",
  "id-aca-authenticationInfo": "id-aca-authenticationInfo",
  "id-aca-accessIdentity": "id-aca-accessIdentity",
  "id-aca-chargingIdentity": "id-aca-chargingIdentity",
  "id-aca-group": "id-aca-group",
  "id-aca-role": "id-aca-role",
  "id-aca-encAttrs": "id-aca-encAttrs",
  "id-qcs-pkixQCSyntax-v1": "id-qcs-pkixQCSyntax-v1",
  "ipAddr-asNumber": "ipAddr-asNumber",
  "ipAddr-asNumberv2": "ipAddr-asNumberv2",
  "id-cct-crs": "id-cct-crs",
  "id-cct-PKIData": "id-cct-PKIData",
  "id-cct-PKIResponse": "id-cct-PKIResponse",
  "id-ppl-anyLanguage": "Any language",
  "id-ppl-inheritAll": "Inherit all",
  "id-ppl-independent": "Independent",
  "OCSP": "OCSP",
  "caIssuers": "CA Issuers",
  "ad_timestamping": "AD Time Stamping",
  "AD_DVCS": "ad dvcs",
  "caRepository": "CA Repository",
  "rpkiManifest": "RPKI Manifest",
  "signedObject": "Signed Object",
  "rpkiNotify": "RPKI Notify",
  "basicOCSPResponse": "Basic OCSP Response",
  "Nonce": "OCSP Nonce",
  "CrlID": "OCSP CRL ID",
  "acceptableResponses": "Acceptable OCSP Responses",
  "noCheck": "OCSP No Check",
  "archiveCutoff": "OCSP Archive Cutoff",
  "serviceLocator": "OCSP Service Locator",
  "extendedStatus": "Extended OCSP Status",
  "valid": "valid",
  "path": "path",
  "trustRoot": "Trust Root",
  "algorithm": "algorithm",
  "RSA-NP-MD5": "md5WithRSA",
  "DES-ECB": "des-ecb",
  "DES-CBC": "des-cbc",
  "DES-OFB": "des-ofb",
  "DES-CFB": "des-cfb",
  "rsaSignature": "rsaSignature",
  "DSA-old": "dsaEncryption-old",
  "DSA-SHA": "dsaWithSHA",
  "RSA-SHA": "shaWithRSAEncryption",
  "DES-EDE": "des-ede",
  "DES-EDE3": "des-ede3",
  "DES-EDE-CBC": "des-ede-cbc",
  "DES-EDE-CFB": "des-ede-cfb",
  "DES-EDE3-CFB": "des-ede3-cfb",
  "DES-EDE-OFB": "des-ede-ofb",
  "DES-EDE3-OFB": "des-ede3-ofb",
  "DESX-CBC": "desx-cbc",
  "SHA": "sha",
  "SHA1": "sha1",
  "DSA-SHA1-old": "dsaWithSHA1-old",
  "RSA-SHA1-2": "sha1WithRSA",
  "RIPEMD160": "ripemd160",
  "RSA-RIPEMD160": "ripemd160WithRSA",
  "BLAKE2BMAC": "blake2bmac",
  "BLAKE2SMAC": "blake2smac",
  "BLAKE2b512": "blake2b512",
  "BLAKE2s256": "blake2s256",
  "SXNetID": "Strong Extranet ID",
  "X500": "directory services (X.500)",
  "X509": "X509",
  "CN": "commonName",
  "SN": "surname",
  "C": "countryName",
  "L": "localityName",
  "ST": "stateOrProvinceName",
  "street": "streetAddress",
  "O": "organizationName",
  "OU": "organizationalUnitName",
  "title": "title",
  "member": "",
  "owner": "",
  "seeAlso": "",
  "name": "name",
  "GN": "givenName",
  "initials": "initials",
  "dnQualifier": "dnQualifier",
  "dmdName": "",
  "role": "role",
  "c3": "countryCode3c",
  "n3": "countryCode3n",
  "X500algorithms": "directory services - algorithms",
  "RSA": "rsa",
  "RSA-MDC2": "mdc2WithRSA",
  "MDC2": "mdc2",
  "id-ce": "id-ce",
  "subjectDirectoryAttributes": "X509v3 Subject Directory Attributes",
  "subjectKeyIdentifier": "X509v3 Subject Key Identifier",
  "keyUsage": "X509v3 Key Usage",
  "privateKeyUsagePeriod": "X509v3 Private Key Usage Period",
  "subjectAltName": "X509v3 Subject Alternative Name",
  "issuerAltName": "X509v3 Issuer Alternative Name",
  "basicConstraints": "X509v3 Basic Constraints",
  "crlNumber": "X509v3 CRL Number",
  "CRLReason": "X509v3 CRL Reason Code",
  "invalidityDate": "Invalidity Date",
  "deltaCRL": "X509v3 Delta CRL Indicator",
  "issuingDistributionPoint": "X509v3 Issuing Distribution Point",
  "certificateIssuer": "X509v3 Certificate Issuer",
  "nameConstraints": "X509v3 Name Constraints",
  "crlDistributionPoints": "X509v3 CRL Distribution Points",
  "certificatePolicies": "X509v3 Certificate Policies",
  "anyPolicy": "X509v3 Any Policy",
  "policyMappings": "X509v3 Policy Mappings",
  "authorityKeyIdentifier": "X509v3 Authority Key Identifier",
  "policyConstraints": "X509v3 Policy Constraints",
  "extendedKeyUsage": "X509v3 Extended Key Usage",
  "authorityAttributeIdentifier": "X509v3 Authority Attribute Identifier",
  "roleSpecCertIdentifier": "X509v3 Role Specification Certificate Identifier",
  "basicAttConstraints": "X509v3 Basic Attribute Certificate Constraints",
  "delegatedNameConstraints": "X509v3 Delegated Name Constraints",
  "timeSpecification": "X509v3 Time Specification",
  "freshestCRL": "X509v3 Freshest CRL",
  "attributeDescriptor": "X509v3 Attribute Descriptor",
  "userNotice": "X509v3 User Notice",
  "sOAIdentifier": "X509v3 Source of Authority Identifier",
  "acceptableCertPolicies": "X509v3 Acceptable Certification Policies",
  "inhibitAnyPolicy": "X509v3 Inhibit Any Policy",
  "targetInformation": "X509v3 AC Targeting",
  "noRevAvail": "X509v3 No Revocation Available",
  "acceptablePrivPolicies": "X509v3 Acceptable Privilege Policies",
  "indirectIssuer": "X509v3 Indirect Issuer",
  "noAssertion": "X509v3 No Assertion",
  "aAissuingDistributionPoint": "X509v3 Attribute Authority Issuing Distribution Point",
  "issuedOnBehalfOf": "X509v3 Issued On Behalf Of",
  "singleUse": "X509v3 Single Use",
  "groupAC": "X509v3 Group Attribute Certificate",
  "allowedAttributeAssignments": "X509v3 Allowed Attribute Assignments",
  "attributeMappings": "X509v3 Attribute Mappings",
  "holderNameConstraints": "X509v3 Holder Name Constraints",
  "authorizationValidation": "X509v3 Authorization Validation",
  "protRestrict": "X509v3 Protocol Restriction",
  "subjectAltPublicKeyInfo": "X509v3 Subject Alternative Public Key Info",
  "altSignatureAlgorithm": "X509v3 Alternative Signature Algorithm",
  "altSignatureValue": "X509v3 Alternative Signature Value",
  "associatedInformation": "X509v3 Associated Information",
  "anyExtendedKeyUsage": "Any Extended Key Usage",
  "Netscape": "Netscape Communications Corp.",
  "nsCertExt": "Netscape Certificate Extension",
  "nsDataType": "Netscape Data Type",
  "nsCertType": "Netscape Cert Type",
  "nsBaseUrl": "Netscape Base Url",
  "nsRevocationUrl": "Netscape Revocation Url",
  "nsCaRevocationUrl": "Netscape CA Revocation Url",
  "nsRenewalUrl": "Netscape Renewal Url",
  "nsCaPolicyUrl": "Netscape CA Policy Url",
  "nsSslServerName": "Netscape SSL Server Name",
  "nsComment": "Netscape Comment",
  "nsCertSequence": "Netscape Certificate Sequence",
  "nsSGC": "Netscape Server Gated Crypto",
  "ORG": "org",
  "DOD": "dod",
  "IANA": "iana",
  "directory": "Directory",
  "mgmt": "Management",
  "experimental": "Experimental",
  "private": "Private",
  "security": "Security",
  "snmpv2": "SNMPv2",
  "enterprises": "Enterprises",
  "dcobject": "dcObject",
  "mime-mhs": "MIME MHS",
  "mime-mhs-headings": "mime-mhs-headings",
  "mime-mhs-bodies": "mime-mhs-bodies",
  "id-hex-partial-message": "id-hex-partial-message",
  "id-hex-multipart-message": "id-hex-multipart-message",
  "ZLIB": "zlib compression",
  "AES-128-ECB": "aes-128-ecb",
  "AES-128-CBC": "aes-128-cbc",
  "AES-128-OFB": "aes-128-ofb",
  "AES-128-CFB": "aes-128-cfb",
  "id-aes128-wrap": "id-aes128-wrap",
  "id-aes128-GCM": "aes-128-gcm",
  "id-aes128-CCM": "aes-128-ccm",
  "id-aes128-wrap-pad": "id-aes128-wrap-pad",
  "AES-192-ECB": "aes-192-ecb",
  "AES-192-CBC": "aes-192-cbc",
  "AES-192-OFB": "aes-192-ofb",
  "AES-192-CFB": "aes-192-cfb",
  "id-aes192-wrap": "id-aes192-wrap",
  "id-aes192-GCM": "aes-192-gcm",
  "id-aes192-CCM": "aes-192-ccm",
  "id-aes192-wrap-pad": "id-aes192-wrap-pad",
  "AES-256-ECB": "aes-256-ecb",
  "AES-256-CBC": "aes-256-cbc",
  "AES-256-OFB": "aes-256-ofb",
  "AES-256-CFB": "aes-256-cfb",
  "id-aes256-wrap": "id-aes256-wrap",
  "id-aes256-GCM": "aes-256-gcm",
  "id-aes256-CCM": "aes-256-ccm",
  "id-aes256-wrap-pad": "id-aes256-wrap-pad",
  "AES-128-XTS": "aes-128-xts",
  "AES-256-XTS": "aes-256-xts",
  "AES-128-CFB1": "aes-128-cfb1",
  "AES-192-CFB1": "aes-192-cfb1",
  "AES-256-CFB1": "aes-256-cfb1",
  "AES-128-CFB8": "aes-128-cfb8",
  "AES-192-CFB8": "aes-192-cfb8",
  "AES-256-CFB8": "aes-256-cfb8",
  "AES-128-CTR": "aes-128-ctr",
  "AES-192-CTR": "aes-192-ctr",
  "AES-256-CTR": "aes-256-ctr",
  "AES-128-OCB": "aes-128-ocb",
  "AES-192-OCB": "aes-192-ocb",
  "AES-256-OCB": "aes-256-ocb",
  "DES-CFB1": "des-cfb1",
  "DES-CFB8": "des-cfb8",
  "DES-EDE3-CFB1": "des-ede3-cfb1",
  "DES-EDE3-CFB8": "des-ede3-cfb8",
  "SHA256": "sha256",
  "SHA384": "sha384",
  "SHA512": "sha512",
  "SHA224": "sha224",
  "SHA512-224": "sha512-224",
  "SHA512-256": "sha512-256",
  "SHA3-224": "sha3-224",
  "SHA3-256": "sha3-256",
  "SHA3-384": "sha3-384",
  "SHA3-512": "sha3-512",
  "SHAKE128": "shake128",
  "SHAKE256": "shake256",
  "id-hmacWithSHA3-224": "hmac-sha3-224",
  "id-hmacWithSHA3-256": "hmac-sha3-256",
  "id-hmacWithSHA3-384": "hmac-sha3-384",
  "id-hmacWithSHA3-512": "hmac-sha3-512",
  "KMAC128": "kmac128",
  "KMAC256": "kmac256",
  "dsa_with_SHA224": "dsa_with_SHA224",
  "dsa_with_SHA256": "dsa_with_SHA256",
  "id-dsa-with-sha384": "dsa_with_SHA384",
  "id-dsa-with-sha512": "dsa_with_SHA512",
  "id-dsa-with-sha3-224": "dsa_with_SHA3-224",
  "id-dsa-with-sha3-256": "dsa_with_SHA3-256",
  "id-dsa-with-sha3-384": "dsa_with_SHA3-384",
  "id-dsa-with-sha3-512": "dsa_with_SHA3-512",
  "id-ecdsa-with-sha3-224": "ecdsa_with_SHA3-224",
  "id-ecdsa-with-sha3-256": "ecdsa_with_SHA3-256",
  "id-ecdsa-with-sha3-384": "ecdsa_with_SHA3-384",
  "id-ecdsa-with-sha3-512": "ecdsa_with_SHA3-512",
  "id-rsassa-pkcs1-v1_5-with-sha3-224": "RSA-SHA3-224",
  "id-rsassa-pkcs1-v1_5-with-sha3-256": "RSA-SHA3-256",
  "id-rsassa-pkcs1-v1_5-with-sha3-384": "RSA-SHA3-384",
  "id-rsassa-pkcs1-v1_5-with-sha3-512": "RSA-SHA3-512",
  "holdInstructionCode": "Hold Instruction Code",
  "holdInstructionNone": "Hold Instruction None",
  "holdInstructionCallIssuer": "Hold Instruction Call Issuer",
  "holdInstructionReject": "Hold Instruction Reject",
  "itu-t-identified-organization": "itu-t-identified-organization",
  "etsi": "etsi",
  "electronic-signature-standard": "electronic-signature-standard",
  "ess-attributes": "ess-attributes",
  "id-aa-ets-mimeType": "id-aa-ets-mimeType",
  "id-aa-ets-longTermValidation": "id-aa-ets-longTermValidation",
  "id-aa-ets-SignaturePolicyDocument": "id-aa-ets-SignaturePolicyDocument",
  "id-aa-ets-archiveTimestampV3": "id-aa-ets-archiveTimestampV3",
  "id-aa-ATSHashIndex": "id-aa-ATSHashIndex",
  "cades": "cades",
  "cades-attributes": "cades-attributes",
  "id-aa-ets-signerAttrV2": "id-aa-ets-signerAttrV2",
  "id-aa-ets-sigPolicyStore": "id-aa-ets-sigPolicyStore",
  "id-aa-ATSHashIndex-v2": "id-aa-ATSHashIndex-v2",
  "id-aa-ATSHashIndex-v3": "id-aa-ATSHashIndex-v3",
  "signedAssertion": "signedAssertion",
  "data": "data",
  "pss": "pss",
  "ucl": "ucl",
  "pilot": "pilot",
  "account": "account",
  "document": "document",
  "room": "room",
  "domain": "Domain",
  "UID": "userId",
  "mail": "rfc822Mailbox",
  "info": "info",
  "photo": "photo",
  "host": "host",
  "manager": "manager",
  "secretary": "secretary",
  "DC": "domainComponent",
  "uid": "uniqueIdentifier",
  "audio": "audio",
  "id-set": "Secure Electronic Transactions",
  "set-ctype": "content types",
  "set-msgExt": "message extensions",
  "set-attr": "set-attr",
  "set-policy": "set-policy",
  "set-certExt": "certificate extensions",
  "set-brand": "set-brand",
  "setct-PANData": "setct-PANData",
  "setct-PANToken": "setct-PANToken",
  "setct-PANOnly": "setct-PANOnly",
  "setct-OIData": "setct-OIData",
  "setct-PI": "setct-PI",
  "setct-PIData": "setct-PIData",
  "setct-PIDataUnsigned": "setct-PIDataUnsigned",
  "setct-HODInput": "setct-HODInput",
  "setct-AuthResBaggage": "setct-AuthResBaggage",
  "setct-AuthRevReqBaggage": "setct-AuthRevReqBaggage",
  "setct-AuthRevResBaggage": "setct-AuthRevResBaggage",
  "setct-CapTokenSeq": "setct-CapTokenSeq",
  "setct-PInitResData": "setct-PInitResData",
  "setct-PI-TBS": "setct-PI-TBS",
  "setct-PResData": "setct-PResData",
  "setct-AuthReqTBS": "setct-AuthReqTBS",
  "setct-AuthResTBS": "setct-AuthResTBS",
  "setct-AuthResTBSX": "setct-AuthResTBSX",
  "setct-AuthTokenTBS": "setct-AuthTokenTBS",
  "setct-CapTokenData": "setct-CapTokenData",
  "setct-CapTokenTBS": "setct-CapTokenTBS",
  "setct-AcqCardCodeMsg": "setct-AcqCardCodeMsg",
  "setct-AuthRevReqTBS": "setct-AuthRevReqTBS",
  "setct-AuthRevResData": "setct-AuthRevResData",
  "setct-AuthRevResTBS": "setct-AuthRevResTBS",
  "setct-CapReqTBS": "setct-CapReqTBS",
  "setct-CapReqTBSX": "setct-CapReqTBSX",
  "setct-CapResData": "setct-CapResData",
  "setct-CapRevReqTBS": "setct-CapRevReqTBS",
  "setct-CapRevReqTBSX": "setct-CapRevReqTBSX",
  "setct-CapRevResData": "setct-CapRevResData",
  "setct-CredReqTBS": "setct-CredReqTBS",
  "setct-CredReqTBSX": "setct-CredReqTBSX",
  "setct-CredResData": "setct-CredResData",
  "setct-CredRevReqTBS": "setct-CredRevReqTBS",
  "setct-CredRevReqTBSX": "setct-CredRevReqTBSX",
  "setct-CredRevResData": "setct-CredRevResData",
  "setct-PCertReqData": "setct-PCertReqData",
  "setct-PCertResTBS": "setct-PCertResTBS",
  "setct-BatchAdminReqData": "setct-BatchAdminReqData",
  "setct-BatchAdminResData": "setct-BatchAdminResData",
  "setct-CardCInitResTBS": "setct-CardCInitResTBS",
  "setct-MeAqCInitResTBS": "setct-MeAqCInitResTBS",
  "setct-RegFormResTBS": "setct-RegFormResTBS",
  "setct-CertReqData": "setct-CertReqData",
  "setct-CertReqTBS": "setct-CertReqTBS",
  "setct-CertResData": "setct-CertResData",
  "setct-CertInqReqTBS": "setct-CertInqReqTBS",
  "setct-ErrorTBS": "setct-ErrorTBS",
  "setct-PIDualSignedTBE": "setct-PIDualSignedTBE",
  "setct-PIUnsignedTBE": "setct-PIUnsignedTBE",
  "setct-AuthReqTBE": "setct-AuthReqTBE",
  "setct-AuthResTBE": "setct-AuthResTBE",
  "setct-AuthResTBEX": "setct-AuthResTBEX",
  "setct-AuthTokenTBE": "setct-AuthTokenTBE",
  "setct-CapTokenTBE": "setct-CapTokenTBE",
  "setct-CapTokenTBEX": "setct-CapTokenTBEX",
  "setct-AcqCardCodeMsgTBE": "setct-AcqCardCodeMsgTBE",
  "setct-AuthRevReqTBE": "setct-AuthRevReqTBE",
  "setct-AuthRevResTBE": "setct-AuthRevResTBE",
  "setct-AuthRevResTBEB": "setct-AuthRevResTBEB",
  "setct-CapReqTBE": "setct-CapReqTBE",
  "setct-CapReqTBEX": "setct-CapReqTBEX",
  "setct-CapResTBE": "setct-CapResTBE",
  "setct-CapRevReqTBE": "setct-CapRevReqTBE",
  "setct-CapRevReqTBEX": "setct-CapRevReqTBEX",
  "setct-CapRevResTBE": "setct-CapRevResTBE",
  "setct-CredReqTBE": "setct-CredReqTBE",
  "setct-CredReqTBEX": "setct-CredReqTBEX",
  "setct-CredResTBE": "setct-CredResTBE",
  "setct-CredRevReqTBE": "setct-CredRevReqTBE",
  "setct-CredRevReqTBEX": "setct-CredRevReqTBEX",
  "setct-CredRevResTBE": "setct-CredRevResTBE",
  "setct-BatchAdminReqTBE": "setct-BatchAdminReqTBE",
  "setct-BatchAdminResTBE": "setct-BatchAdminResTBE",
  "setct-RegFormReqTBE": "setct-RegFormReqTBE",
  "setct-CertReqTBE": "setct-CertReqTBE",
  "setct-CertReqTBEX": "setct-CertReqTBEX",
  "setct-CertResTBE": "setct-CertResTBE",
  "setct-CRLNotificationTBS": "setct-CRLNotificationTBS",
  "setct-CRLNotificationResTBS": "setct-CRLNotificationResTBS",
  "setct-BCIDistributionTBS": "setct-BCIDistributionTBS",
  "setext-genCrypt": "generic cryptogram",
  "setext-miAuth": "merchant initiated auth",
  "setext-pinSecure": "setext-pinSecure",
  "setext-pinAny": "setext-pinAny",
  "setext-track2": "setext-track2",
  "setext-cv": "additional verification",
  "set-policy-root": "set-policy-root",
  "setCext-hashedRoot": "setCext-hashedRoot",
  "setCext-certType": "setCext-certType",
  "setCext-merchData": "setCext-merchData",
  "setCext-cCertRequired": "setCext-cCertRequired",
  "setCext-tunneling": "setCext-tunneling",
  "setCext-setExt": "setCext-setExt",
  "setCext-setQualf": "setCext-setQualf",
  "setCext-PGWYcapabilities": "setCext-PGWYcapabilities",
  "setCext-TokenIdentifier": "setCext-TokenIdentifier",
  "setCext-Track2Data": "setCext-Track2Data",
  "setCext-TokenType": "setCext-TokenType",
  "setCext-IssuerCapabilities": "setCext-IssuerCapabilities",
  "setAttr-Cert": "setAttr-Cert",
  "setAttr-PGWYcap": "payment gateway capabilities",
  "setAttr-TokenType": "setAttr-TokenType",
  "setAttr-IssCap": "issuer capabilities",
  "set-rootKeyThumb": "set-rootKeyThumb",
  "set-addPolicy": "set-addPolicy",
  "setAttr-Token-EMV": "setAttr-Token-EMV",
  "setAttr-Token-B0Prime": "setAttr-Token-B0Prime",
  "setAttr-IssCap-CVM": "setAttr-IssCap-CVM",
  "setAttr-IssCap-T2": "setAttr-IssCap-T2",
  "setAttr-IssCap-Sig": "setAttr-IssCap-Sig",
  "setAttr-GenCryptgrm": "generate cryptogram",
  "setAttr-T2Enc": "encrypted track 2",
  "setAttr-T2cleartxt": "cleartext track 2",
  "setAttr-TokICCsig": "ICC or token signature",
  "setAttr-SecDevSig": "secure device signature",
  "set-brand-IATA-ATA": "set-brand-IATA-ATA",
  "set-brand-Diners": "set-brand-Diners",
  "set-brand-AmericanExpress": "set-brand-AmericanExpress",
  "set-brand-JCB": "set-brand-JCB",
  "set-brand-Visa": "set-brand-Visa",
  "set-brand-MasterCard": "set-brand-MasterCard",
  "set-brand-Novus": "set-brand-Novus",
  "DES-CDMF": "des-cdmf",
  "rsaOAEPEncryptionSET": "rsaOAEPEncryptionSET",
  "Oakley-EC2N-3": "ipsec3",
  "Oakley-EC2N-4": "ipsec4",
  "whirlpool": "whirlpool",
  "cryptopro": "cryptopro",
  "cryptocom": "cryptocom",
  "id-tc26": "id-tc26",
  "id-GostR3411-94-with-GostR3410-2001": "GOST R 34.11-94 with GOST R 34.10-2001",
  "id-GostR3411-94-with-GostR3410-94": "GOST R 34.11-94 with GOST R 34.10-94",
  "md_gost94": "GOST R 34.11-94",
  "id-HMACGostR3411-94": "HMAC GOST 34.11-94",
  "gost2001": "GOST R 34.10-2001",
  "gost94": "GOST R 34.10-94",
  "gost89": "GOST 28147-89",
  "gost89-cnt": "gost89-cnt",
  "gost89-cnt-12": "gost89-cnt-12",
  "gost89-cbc": "gost89-cbc",
  "gost89-ecb": "gost89-ecb",
  "gost89-ctr": "gost89-ctr",
  "gost-mac": "GOST 28147-89 MAC",
  "gost-mac-12": "gost-mac-12",
  "prf-gostr3411-94": "GOST R 34.11-94 PRF",
  "id-GostR3410-2001DH": "GOST R 34.10-2001 DH",
  "id-GostR3410-94DH": "GOST R 34.10-94 DH",
  "id-Gost28147-89-CryptoPro-KeyMeshing": "id-Gost28147-89-CryptoPro-KeyMeshing",
  "id-Gost28147-89-None-KeyMeshing": "id-Gost28147-89-None-KeyMeshing",
  "id-GostR3411-94-TestParamSet": "id-GostR3411-94-TestParamSet",
  "id-GostR3411-94-CryptoProParamSet": "id-GostR3411-94-CryptoProParamSet",
  "id-Gost28147-89-TestParamSet": "id-Gost28147-89-TestParamSet",
  "id-Gost28147-89-CryptoPro-A-ParamSet": "id-Gost28147-89-CryptoPro-A-ParamSet",
  "id-Gost28147-89-CryptoPro-B-ParamSet": "id-Gost28147-89-CryptoPro-B-ParamSet",
  "id-Gost28147-89-CryptoPro-C-ParamSet": "id-Gost28147-89-CryptoPro-C-ParamSet",
  "id-Gost28147-89-CryptoPro-D-ParamSet": "id-Gost28147-89-CryptoPro-D-ParamSet",
  "id-Gost28147-89-CryptoPro-Oscar-1-1-ParamSet": "id-Gost28147-89-CryptoPro-Oscar-1-1-ParamSet",
  "id-Gost28147-89-CryptoPro-Oscar-1-0-ParamSet": "id-Gost28147-89-CryptoPro-Oscar-1-0-ParamSet",
  "id-Gost28147-89-CryptoPro-RIC-1-ParamSet": "id-Gost28147-89-CryptoPro-RIC-1-ParamSet",
  "id-GostR3410-94-TestParamSet": "id-GostR3410-94-TestParamSet",
  "id-GostR3410-94-CryptoPro-A-ParamSet": "id-GostR3410-94-CryptoPro-A-ParamSet",
  "id-GostR3410-94-CryptoPro-B-ParamSet": "id-GostR3410-94-CryptoPro-B-ParamSet",
  "id-GostR3410-94-CryptoPro-C-ParamSet": "id-GostR3410-94-CryptoPro-C-ParamSet",
  "id-GostR3410-94-CryptoPro-D-ParamSet": "id-GostR3410-94-CryptoPro-D-ParamSet",
  "id-GostR3410-94-CryptoPro-XchA-ParamSet": "id-GostR3410-94-CryptoPro-XchA-ParamSet",
  "id-GostR3410-94-CryptoPro-XchB-ParamSet": "id-GostR3410-94-CryptoPro-XchB-ParamSet",
  "id-GostR3410-94-CryptoPro-XchC-ParamSet": "id-GostR3410-94-CryptoPro-XchC-ParamSet",
  "id-GostR3410-2001-TestParamSet": "id-GostR3410-2001-TestParamSet",
  "id-GostR3410-2001-CryptoPro-A-ParamSet": "id-GostR3410-2001-CryptoPro-A-ParamSet",
  "id-GostR3410-2001-CryptoPro-B-ParamSet": "id-GostR3410-2001-CryptoPro-B-ParamSet",
  "id-GostR3410-2001-CryptoPro-C-ParamSet": "id-GostR3410-2001-CryptoPro-C-ParamSet",
  "id-GostR3410-2001-CryptoPro-XchA-ParamSet": "id-GostR3410-2001-CryptoPro-XchA-ParamSet",
  "id-GostR3410-2001-CryptoPro-XchB-ParamSet": "id-GostR3410-2001-CryptoPro-XchB-ParamSet",
  "id-GostR3410-94-a": "id-GostR3410-94-a",
  "id-GostR3410-94-aBis": "id-GostR3410-94-aBis",
  "id-GostR3410-94-b": "id-GostR3410-94-b",
  "id-GostR3410-94-bBis": "id-GostR3410-94-bBis",
  "id-Gost28147-89-cc": "GOST 28147-89 Cryptocom ParamSet",
  "gost94cc": "GOST 34.10-94 Cryptocom",
  "gost2001cc": "GOST 34.10-2001 Cryptocom",
  "id-GostR3411-94-with-GostR3410-94-cc": "GOST R 34.11-94 with GOST R 34.10-94 Cryptocom",
  "id-GostR3411-94-with-GostR3410-2001-cc": "GOST R 34.11-94 with GOST R 34.10-2001 Cryptocom",
  "id-GostR3410-2001-ParamSet-cc": "GOST R 3410-2001 Parameter Set Cryptocom",
  "id-tc26-algorithms": "id-tc26-algorithms",
  "id-tc26-sign": "id-tc26-sign",
  "gost2012_256": "GOST R 34.10-2012 with 256 bit modulus",
  "gost2012_512": "GOST R 34.10-2012 with 512 bit modulus",
  "id-tc26-digest": "id-tc26-digest",
  "md_gost12_256": "GOST R 34.11-2012 with 256 bit hash",
  "md_gost12_512": "GOST R 34.11-2012 with 512 bit hash",
  "id-tc26-signwithdigest": "id-tc26-signwithdigest",
  "id-tc26-signwithdigest-gost3410-2012-256": "GOST R 34.10-2012 with GOST R 34.11-2012 (256 bit)",
  "id-tc26-signwithdigest-gost3410-2012-512": "GOST R 34.10-2012 with GOST R 34.11-2012 (512 bit)",
  "id-tc26-mac": "id-tc26-mac",
  "id-tc26-hmac-gost-3411-2012-256": "HMAC GOST 34.11-2012 256 bit",
  "id-tc26-hmac-gost-3411-2012-512": "HMAC GOST 34.11-2012 512 bit",
  "id-tc26-cipher": "id-tc26-cipher",
  "id-tc26-cipher-gostr3412-2015-magma": "id-tc26-cipher-gostr3412-2015-magma",
  "magma-ctr-acpkm": "magma-ctr-acpkm",
  "magma-ctr-acpkm-omac": "magma-ctr-acpkm-omac",
  "id-tc26-cipher-gostr3412-2015-kuznyechik": "id-tc26-cipher-gostr3412-2015-kuznyechik",
  "kuznyechik-ctr-acpkm": "kuznyechik-ctr-acpkm",
  "kuznyechik-ctr-acpkm-omac": "kuznyechik-ctr-acpkm-omac",
  "id-tc26-agreement": "id-tc26-agreement",
  "id-tc26-agreement-gost-3410-2012-256": "id-tc26-agreement-gost-3410-2012-256",
  "id-tc26-agreement-gost-3410-2012-512": "id-tc26-agreement-gost-3410-2012-512",
  "id-tc26-wrap": "id-tc26-wrap",
  "id-tc26-wrap-gostr3412-2015-magma": "id-tc26-wrap-gostr3412-2015-magma",
  "magma-kexp15": "magma-kexp15",
  "id-tc26-wrap-gostr3412-2015-kuznyechik": "id-tc26-wrap-gostr3412-2015-kuznyechik",
  "kuznyechik-kexp15": "kuznyechik-kexp15",
  "id-tc26-constants": "id-tc26-constants",
  "id-tc26-sign-constants": "id-tc26-sign-constants",
  "id-tc26-gost-3410-2012-256-constants": "id-tc26-gost-3410-2012-256-constants",
  "id-tc26-gost-3410-2012-256-paramSetA": "GOST R 34.10-2012 (256 bit) ParamSet A",
  "id-tc26-gost-3410-2012-256-paramSetB": "GOST R 34.10-2012 (256 bit) ParamSet B",
  "id-tc26-gost-3410-2012-256-paramSetC": "GOST R 34.10-2012 (256 bit) ParamSet C",
  "id-tc26-gost-3410-2012-256-paramSetD": "GOST R 34.10-2012 (256 bit) ParamSet D",
  "id-tc26-gost-3410-2012-512-constants": "id-tc26-gost-3410-2012-512-constants",
  "id-tc26-gost-3410-2012-512-paramSetTest": "GOST R 34.10-2012 (512 bit) testing parameter set",
  "id-tc26-gost-3410-2012-512-paramSetA": "GOST R 34.10-2012 (512 bit) ParamSet A",
  "id-tc26-gost-3410-2012-512-paramSetB": "GOST R 34.10-2012 (512 bit) ParamSet B",
  "id-tc26-gost-3410-2012-512-paramSetC": "GOST R 34.10-2012 (512 bit) ParamSet C",
  "id-tc26-digest-constants": "id-tc26-digest-constants",
  "id-tc26-cipher-constants": "id-tc26-cipher-constants",
  "id-tc26-gost-28147-constants": "id-tc26-gost-28147-constants",
  "id-tc26-gost-28147-param-Z": "GOST 28147-89 TC26 parameter set",
  "INN": "INN",
  "OGRN": "OGRN",
  "SNILS": "SNILS",
  "OGRNIP": "OGRNIP",
  "subjectSignTool": "Signing Tool of Subject",
  "issuerSignTool": "Signing Tool of Issuer",
  "classSignTool": "Class of Signing Tool",
  "classSignToolKC1": "Class of Signing Tool KC1",
  "classSignToolKC2": "Class of Signing Tool KC2",
  "classSignToolKC3": "Class of Signing Tool KC3",
  "classSignToolKB1": "Class of Signing Tool KB1",
  "classSignToolKB2": "Class of Signing Tool KB2",
  "classSignToolKA1": "Class of Signing Tool KA1",
  "kuznyechik-ecb": "kuznyechik-ecb",
  "kuznyechik-ctr": "kuznyechik-ctr",
  "kuznyechik-ofb": "kuznyechik-ofb",
  "kuznyechik-cbc": "kuznyechik-cbc",
  "kuznyechik-cfb": "kuznyechik-cfb",
  "kuznyechik-mac": "kuznyechik-mac",
  "magma-ecb": "magma-ecb",
  "magma-ctr": "magma-ctr",
  "magma-ofb": "magma-ofb",
  "magma-cbc": "magma-cbc",
  "magma-cfb": "magma-cfb",
  "magma-mac": "magma-mac",
  "CAMELLIA-128-CBC": "camellia-128-cbc",
  "CAMELLIA-192-CBC": "camellia-192-cbc",
  "CAMELLIA-256-CBC": "camellia-256-cbc",
  "id-camellia128-wrap": "id-camellia128-wrap",
  "id-camellia192-wrap": "id-camellia192-wrap",
  "id-camellia256-wrap": "id-camellia256-wrap",
  "CAMELLIA-128-ECB": "camellia-128-ecb",
  "CAMELLIA-128-OFB": "camellia-128-ofb",
  "CAMELLIA-128-CFB": "camellia-128-cfb",
  "CAMELLIA-128-GCM": "camellia-128-gcm",
  "CAMELLIA-128-CCM": "camellia-128-ccm",
  "CAMELLIA-128-CTR": "camellia-128-ctr",
  "CAMELLIA-128-CMAC": "camellia-128-cmac",
  "CAMELLIA-192-ECB": "camellia-192-ecb",
  "CAMELLIA-192-OFB": "camellia-192-ofb",
  "CAMELLIA-192-CFB": "camellia-192-cfb",
  "CAMELLIA-192-GCM": "camellia-192-gcm",
  "CAMELLIA-192-CCM": "camellia-192-ccm",
  "CAMELLIA-192-CTR": "camellia-192-ctr",
  "CAMELLIA-192-CMAC": "camellia-192-cmac",
  "CAMELLIA-256-ECB": "camellia-256-ecb",
  "CAMELLIA-256-OFB": "camellia-256-ofb",
  "CAMELLIA-256-CFB": "camellia-256-cfb",
  "CAMELLIA-256-GCM": "camellia-256-gcm",
  "CAMELLIA-256-CCM": "camellia-256-ccm",
  "CAMELLIA-256-CTR": "camellia-256-ctr",
  "CAMELLIA-256-CMAC": "camellia-256-cmac",
  "CAMELLIA-128-CFB1": "camellia-128-cfb1",
  "CAMELLIA-192-CFB1": "camellia-192-cfb1",
  "CAMELLIA-256-CFB1": "camellia-256-cfb1",
  "CAMELLIA-128-CFB8": "camellia-128-cfb8",
  "CAMELLIA-192-CFB8": "camellia-192-cfb8",
  "CAMELLIA-256-CFB8": "camellia-256-cfb8",
  "ARIA-128-ECB": "aria-128-ecb",
  "ARIA-128-CBC": "aria-128-cbc",
  "ARIA-128-CFB": "aria-128-cfb",
  "ARIA-128-OFB": "aria-128-ofb",
  "ARIA-128-CTR": "aria-128-ctr",
  "ARIA-192-ECB": "aria-192-ecb",
  "ARIA-192-CBC": "aria-192-cbc",
  "ARIA-192-CFB": "aria-192-cfb",
  "ARIA-192-OFB": "aria-192-ofb",
  "ARIA-192-CTR": "aria-192-ctr",
  "ARIA-256-ECB": "aria-256-ecb",
  "ARIA-256-CBC": "aria-256-cbc",
  "ARIA-256-CFB": "aria-256-cfb",
  "ARIA-256-OFB": "aria-256-ofb",
  "ARIA-256-CTR": "aria-256-ctr",
  "ARIA-128-CFB1": "aria-128-cfb1",
  "ARIA-192-CFB1": "aria-192-cfb1",
  "ARIA-256-CFB1": "aria-256-cfb1",
  "ARIA-128-CFB8": "aria-128-cfb8",
  "ARIA-192-CFB8": "aria-192-cfb8",
  "ARIA-256-CFB8": "aria-256-cfb8",
  "ARIA-128-CCM": "aria-128-ccm",
  "ARIA-192-CCM": "aria-192-ccm",
  "ARIA-256-CCM": "aria-256-ccm",
  "ARIA-128-GCM": "aria-128-gcm",
  "ARIA-192-GCM": "aria-192-gcm",
  "ARIA-256-GCM": "aria-256-gcm",
  "KISA": "kisa",
  "SEED-ECB": "seed-ecb",
  "SEED-CBC": "seed-cbc",
  "SEED-CFB": "seed-cfb",
  "SEED-OFB": "seed-ofb",
  "SM4-ECB": "sm4-ecb",
  "SM4-CBC": "sm4-cbc",
  "SM4-OFB": "sm4-ofb",
  "SM4-CFB": "sm4-cfb",
  "SM4-CFB1": "sm4-cfb1",
  "SM4-CFB8": "sm4-cfb8",
  "SM4-CTR": "sm4-ctr",
  "SM4-GCM": "sm4-gcm",
  "SM4-CCM": "sm4-ccm",
  "SM4-XTS": "sm4-xts",
  "HMAC": "hmac",
  "CMAC": "cmac",
  "RC4-HMAC-MD5": "rc4-hmac-md5",
  "AES-128-CBC-HMAC-SHA1": "aes-128-cbc-hmac-sha1",
  "AES-192-CBC-HMAC-SHA1": "aes-192-cbc-hmac-sha1",
  "AES-256-CBC-HMAC-SHA1": "aes-256-cbc-hmac-sha1",
  "AES-128-CBC-HMAC-SHA256": "aes-128-cbc-hmac-sha256",
  "AES-192-CBC-HMAC-SHA256": "aes-192-cbc-hmac-sha256",
  "AES-256-CBC-HMAC-SHA256": "aes-256-cbc-hmac-sha256",
  "ChaCha20-Poly1305": "chacha20-poly1305",
  "ChaCha20": "chacha20",
  "dhpublicnumber": "X9.42 DH",
  "brainpoolP160r1": "brainpoolP160r1",
  "brainpoolP160t1": "brainpoolP160t1",
  "brainpoolP192r1": "brainpoolP192r1",
  "brainpoolP192t1": "brainpoolP192t1",
  "brainpoolP224r1": "brainpoolP224r1",
  "brainpoolP224t1": "brainpoolP224t1",
  "brainpoolP256r1": "brainpoolP256r1",
  "brainpoolP256r1tls13": "brainpoolP256r1tls13",
  "brainpoolP256t1": "brainpoolP256t1",
  "brainpoolP320r1": "brainpoolP320r1",
  "brainpoolP320t1": "brainpoolP320t1",
  "brainpoolP384r1": "brainpoolP384r1",
  "brainpoolP384r1tls13": "brainpoolP384r1tls13",
  "brainpoolP384t1": "brainpoolP384t1",
  "brainpoolP512r1": "brainpoolP512r1",
  "brainpoolP512r1tls13": "brainpoolP512r1tls13",
  "brainpoolP512t1": "brainpoolP512t1",
  "dhSinglePass-stdDH-sha1kdf-scheme": "dhSinglePass-stdDH-sha1kdf-scheme",
  "dhSinglePass-stdDH-sha224kdf-scheme": "dhSinglePass-stdDH-sha224kdf-scheme",
  "dhSinglePass-stdDH-sha256kdf-scheme": "dhSinglePass-stdDH-sha256kdf-scheme",
  "dhSinglePass-stdDH-sha384kdf-scheme": "dhSinglePass-stdDH-sha384kdf-scheme",
  "dhSinglePass-stdDH-sha512kdf-scheme": "dhSinglePass-stdDH-sha512kdf-scheme",
  "dhSinglePass-cofactorDH-sha1kdf-scheme": "dhSinglePass-cofactorDH-sha1kdf-scheme",
  "dhSinglePass-cofactorDH-sha224kdf-scheme": "dhSinglePass-cofactorDH-sha224kdf-scheme",
  "dhSinglePass-cofactorDH-sha256kdf-scheme": "dhSinglePass-cofactorDH-sha256kdf-scheme",
  "dhSinglePass-cofactorDH-sha384kdf-scheme": "dhSinglePass-cofactorDH-sha384kdf-scheme",
  "dhSinglePass-cofactorDH-sha512kdf-scheme": "dhSinglePass-cofactorDH-sha512kdf-scheme",
  "dh-std-kdf": "dh-std-kdf",
  "dh-cofactor-kdf": "dh-cofactor-kdf",
  "ct_precert_scts": "CT Precertificate SCTs",
  "ct_precert_poison": "CT Precertificate Poison",
  "ct_precert_signer": "CT Precertificate Signer",
  "ct_cert_scts": "CT Certificate SCTs",
  "jurisdictionL": "jurisdictionLocalityName",
  "jurisdictionST": "jurisdictionStateOrProvinceName",
  "jurisdictionC": "jurisdictionCountryName",
  "id-scrypt": "scrypt",
  "TLS1-PRF": "tls1-prf",
  "HKDF": "hkdf",
  "SSHKDF": "sshkdf",
  "SSKDF": "sskdf",
  "X942KDF": "x942kdf",
  "X963KDF": "x963kdf",
  "id-pkinit": "id-pkinit",
  "pkInitClientAuth": "PKINIT Client Auth",
  "pkInitKDC": "Signing KDC Response",
  "X25519": "X25519",
  "X448": "X448",
  "ED25519": "ED25519",
  "ED448": "ED448",
  "KxRSA": "kx-rsa",
  "KxECDHE": "kx-ecdhe",
  "KxDHE": "kx-dhe",
  "KxECDHE-PSK": "kx-ecdhe-psk",
  "KxDHE-PSK": "kx-dhe-psk",
  "KxRSA_PSK": "kx-rsa-psk",
  "KxPSK": "kx-psk",
  "KxSRP": "kx-srp",
  "KxGOST": "kx-gost",
  "KxGOST18": "kx-gost18",
  "KxANY": "kx-any",
  "AuthRSA": "auth-rsa",
  "AuthECDSA": "auth-ecdsa",
  "AuthPSK": "auth-psk",
  "AuthDSS": "auth-dss",
  "AuthGOST01": "auth-gost01",
  "AuthGOST12": "auth-gost12",
  "AuthSRP": "auth-srp",
  "AuthNULL": "auth-null",
  "AuthANY": "auth-any",
  "Poly1305": "poly1305",
  "SipHash": "siphash",
  "ffdhe2048": "ffdhe2048",
  "ffdhe3072": "ffdhe3072",
  "ffdhe4096": "ffdhe4096",
  "ffdhe6144": "ffdhe6144",
  "ffdhe8192": "ffdhe8192",
  "modp_1536": "modp_1536",
  "modp_2048": "modp_2048",
  "modp_3072": "modp_3072",
  "modp_4096": "modp_4096",
  "modp_6144": "modp_6144",
  "modp_8192": "modp_8192",
  "ISO-UA": "ISO-UA",
  "ua-pki": "ua-pki",
  "dstu28147": "DSTU Gost 28147-2009",
  "dstu28147-ofb": "DSTU Gost 28147-2009 OFB mode",
  "dstu28147-cfb": "DSTU Gost 28147-2009 CFB mode",
  "dstu28147-wrap": "DSTU Gost 28147-2009 key wrap",
  "hmacWithDstu34311": "HMAC DSTU Gost 34311-95",
  "dstu34311": "DSTU Gost 34311-95",
  "dstu4145le": "DSTU 4145-2002 little endian",
  "dstu4145be": "DSTU 4145-2002 big endian",
  "uacurve0": "DSTU curve 0",
  "uacurve1": "DSTU curve 1",
  "uacurve2": "DSTU curve 2",
  "uacurve3": "DSTU curve 3",
  "uacurve4": "DSTU curve 4",
  "uacurve5": "DSTU curve 5",
  "uacurve6": "DSTU curve 6",
  "uacurve7": "DSTU curve 7",
  "uacurve8": "DSTU curve 8",
  "uacurve9": "DSTU curve 9",
  "AES-128-SIV": "aes-128-siv",
  "AES-192-SIV": "aes-192-siv",
  "AES-256-SIV": "aes-256-siv",
  "oracle-organization": "Oracle organization",
  "oracle-jdk-trustedkeyusage": "Trusted key usage (Oracle)",
  "brotli": "Brotli compression",
  "zstd": "Zstandard compression"
}